[package]
name = "embedded_hello_world"
version = "0.1.0"
edition = "2021"
authors = ["Petros Trakadas <pit.trak@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aux6 = { path = "auxiliary" }