[package]
name = "led_and_delay_abstractions"
version = "0.1.0"
edition = "2021"
authors = ["Petros Trakadas <pit.trak@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aux5 = { path = "auxiliary" }
volatile = "0.4.6"